social_media/post/urls.py
from django.urls import path, include
from post import views
import social_media.settings 
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from .views import ModelViewSet

app_name = "post"

router = DefaultRouter()
router.register(r'posts', ModelViewSet)

urlpatterns = [
    path('', views.posts, name="posts"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('addpost/', views.addPost, name="addPost"),
    path('update/<int:id>', views.updatePost, name="updatePost"),
    path('delete/<int:id>', views.deletePost, name="deletePost"),

]
urlpatterns += static(social_media.settings.MEDIA_URL, document_root=social_media.settings.MEDIA_ROOT)

social_media/social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from post import views
import social_media.settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from post.views import ModelViewSet
from user.views import UserModelViewSet

router = DefaultRouter()
router.register(r'posts', ModelViewSet)
router.register(r'user_profiles', UserModelViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('user/', include("user.urls")),
    path('posts/', include("post.urls")),
    path('api/', include(router.urls), name='api'),
    
]
urlpatterns += static(social_media.settings.MEDIA_URL, document_root=social_media.settings.MEDIA_ROOT)

social_media/user/urls.py
from django.urls import path, include
from user import views

from rest_framework.routers import DefaultRouter
from .views import UserModelViewSet

app_name = "user"

router = DefaultRouter()
router.register(r'user_profiles', UserModelViewSet)

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('register/', views.register, name="register"),
    path('logout/', views.logoutUser, name="logout"),
    path('profile/', views.profileUser, name="profileUser"),
    path('profile_author/<int:author_id>/', views.profileAuthor, name="profileAuthor"),
    path('settings/', views.userSettings, name="settings"),
    path('change_username/', views.change_username, name="change_username"),
    path('change_password/', views.change_password, name="change_password"),
    path('delete_profile/', views.delete_profile, name="delete_profile"),
]

social_media/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">Social Media</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Anasayfa &nbsp; <i class="fa-solid fa-house"></i> <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'post:posts' %}" title="Keşfet">Keşfet &nbsp; <i class="fa-solid fa-magnifying-glass"></i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'post:dashboard' %}" title="Keşfet">Gönderilerim &nbsp; <i class="fa-solid fa-list"></i></a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="/api/">API</a>
        </li>
        
        
      </ul>

          
      {% load static %}

      <ul class="navbar-nav ml-auto">
        
        {% if request.user.is_authenticated %}

            <img class="profile-photo-navbar" src="{% static 'img/placeholder.png' %}" alt="Profile Photo">
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle username-navbar" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{request.user}}</a>  
              
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="{% url 'user:profileUser' %}">Profil &nbsp; <i class="fa-regular fa-user"></i></a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'user:settings' %}">Ayarlar &nbsp; <i class="fa-solid fa-gear"></i></a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'user:logout' %}">Çıkış Yap &nbsp; <i class="fa-solid fa-right-from-bracket"></i></a>
              </div>

            </div>
          
            

            
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap &nbsp; <i class="fa-solid fa-user"></i> </a>
          </li>
        
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:register' %}">Kayıt Ol &nbsp; <i class="fa-solid fa-user-plus"></i> </a>
          </li>
        {% endif %}
          
        
        
      </ul>

      
    </div>
  </nav>