social_media/post/urls.py
from django.urls import path, include
from post import views
import social_media.settings 
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from .views import ModelViewSet

app_name = "post"

router = DefaultRouter()
router.register(r'posts', ModelViewSet)

urlpatterns = [
    path('', views.posts, name="posts"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('addpost/', views.addPost, name="addPost"),
    path('update/<int:id>', views.updatePost, name="updatePost"),
    path('delete/<int:id>', views.deletePost, name="deletePost"),

]
urlpatterns += static(social_media.settings.MEDIA_URL, document_root=social_media.settings.MEDIA_ROOT)

social_media/social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from post import views
import social_media.settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from post.views import ModelViewSet
from user.views import UserModelViewSet

router = DefaultRouter()
router.register(r'posts', ModelViewSet)
router.register(r'user_profiles', UserModelViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('user/', include("user.urls")),
    path('posts/', include("post.urls")),
    path('api/', include(router.urls), name='api'),
    
]
urlpatterns += static(social_media.settings.MEDIA_URL, document_root=social_media.settings.MEDIA_ROOT)

social_media/user/urls.py
from django.urls import path, include
from user import views

from rest_framework.routers import DefaultRouter
from .views import UserModelViewSet

app_name = "user"

router = DefaultRouter()
router.register(r'user_profiles', UserModelViewSet)

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('register/', views.register, name="register"),
    path('logout/', views.logoutUser, name="logout"),
    path('profile/', views.profileUser, name="profileUser"),
    path('profile_author/<int:author_id>/', views.profileAuthor, name="profileAuthor"),
    path('settings/', views.userSettings, name="settings"),
    path('change_username/', views.change_username, name="change_username"),
    path('change_password/', views.change_password, name="change_password"),
    path('delete_profile/', views.delete_profile, name="delete_profile"),
]

social_media/user/models.py
from django.db import models
from django.contrib.auth.models import User  

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followers_count = models.IntegerField(default=0)

social_media/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

class LoginForm(forms.Form):
    username = forms.CharField(label="Kullanıcı adı", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label="Parola", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50,label="Kullanıcı adı")
    password = forms.CharField(max_length=50,label="Parola", widget=forms.PasswordInput)
    confirm_password = forms.CharField(max_length=50, label="Parolayı doğrulayın", widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Parolalar eşleşmiyor...")
        
        
        values = {
            "username":username,
            "password":password
        }

        return values
    
class ChangeUsernameForm(forms.Form):
    new_username = forms.CharField(label="Yeni Kullanıcı adı", max_length=50)

    def clean_new_username(self):
        new_username = self.cleaned_data['new_username']
        # Yeni kullanıcı adının kullanılabilir olduğunu kontrol edin
        if User.objects.filter(username=new_username).exists():
            raise forms.ValidationError('Bu kullanıcı adı zaten kullanılıyor.')
        return new_username
    
class ChangePasswordForm(forms.Form):
    new_password = forms.CharField(label="Yeni Parola", max_length=100, widget=forms.PasswordInput)

social_media/user/views.py
from django.shortcuts import render,redirect, get_object_or_404
from user.forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import login,logout,authenticate
from django.db import IntegrityError
from post.models import Post
from user.forms import ChangeUsernameForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .models import UserProfile
from django.http import HttpResponse

from rest_framework import viewsets
from .models import User
from .serializers import UserModelSerializer


def loginUser (request):
    form = LoginForm(request.POST or None)
    context = {
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username, password = password)

        if user is None:
            messages.info(request, "Kullanıcı adı veya parola hatalı")
            return render(request, "user/login.html", context)
        
        messages.success(request, "Başarıyla giriş yaptınız")
        login(request, user)

        return redirect("index")
    return render(request, "user/login.html", context)

    return render(request, "user/login.html")

def register (request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        try:
            newUser = User(username = username)
            newUser.set_password(password)
            newUser.save()
            login(request, newUser)
            messages.success(request, "Başarıyla kayıt oldunuz")
            return redirect("index")
        
        except IntegrityError:
            messages.info(request, "Bu kullanıcı adı alınmış")

    context = {
        "form": form
    }
   
   
    return render(request, "user/register.html",context)

def logoutUser (request):
    logout(request)
    messages.success(request, "Başarıyla çıkış yaptınız")
    return redirect("index")


def profileUser(request):
    if not request.user.is_authenticated:
        messages.info(request, "Profilinizi görüntüleyebilmek için giriş yapmalısınız.")
        return redirect("user:login")
    user = request.user
    registiration_date = user.date_joined
    posts = Post.objects.filter(author = request.user)

    context = {
        'user':user,
        'registiration_date' :registiration_date,
        'posts':posts
    }

    return render(request, "user/Userprofile.html", context)

def profileAuthor(request, author_id):
    author = get_object_or_404(User, id=author_id)
    registiration_date = author.date_joined
    posts = Post.objects.filter(author= author_id)

    context = {
        'author':author,
        'registiration_date' :registiration_date,
        'posts':posts
    }

    return render(request, "user/profileAuthor.html", context)

def userSettings(request):
    if not request.user.is_authenticated:
        messages.info(request, "Ayarlar sayfasını görüntüleyebilmek için giriş yapmalısınız.")
        return redirect("user:login")
    return render(request, "user/settings.html")

def change_username(request):
    if not request.user.is_authenticated:
        return redirect("user:login")
    if request.method == "POST":
        form = ChangeUsernameForm(request.POST)
        if form.is_valid():
            new_username = form.cleaned_data["new_username"]
            request.user.username = new_username
            request.user.save()
            messages.success(request, "Kullanıcı adı başarıyla değiştirildi")
            return redirect("user:settings")
        
    else:
        form = ChangeUsernameForm()

    return render(request, "user/change_username.html", {"form":form})

def change_password(request):
    if not request.user.is_authenticated:
        return redirect("user:login")
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Parola başarıyla değiştirildi")
            return redirect("user:settings")
    else:
        form = PasswordChangeForm(request.user)

    return render(request, "user/change_password.html", {"form": form})


def delete_profile(request):
    if not request.user.is_authenticated:
        return redirect("user:login")
    if request.method == "POST":
        request.user.delete()
        messages.success(request, "Hesabınız başarıyla silindi")
        return redirect("index")
    else:
        return render(request, "user/delete_profile_confirmation.html")
    

def follower(request):
    followers_count = UserProfile.objects.get(user_id = 1)
    followers_count = {
        "followers_count":followers_count,
    }
    return render(request, "user/profileAuthor.html", followers_count)


# Rest Framework ------------------------------------


class UserModelViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserModelSerializer

social_media/templates/user/Userprofile.html
{% extends 'layout.html' %}
{% load static %}


{% block body %}
    <h3 class="header-text">Profilim</h3>
    <hr>
    <br>
    <img class="profile-photo" src="{% static 'img/placeholder.png' %}" alt="Profile Photo">
    <br>
    <p class="profile-text" >Profil Resmi</p>
    <br>
    <hr>
    <p class="profile-text">Kullanıcı adı : &nbsp; {{user.username}} </p>
    <p class="profile-text">Kayıt olma tarihi : &nbsp; {{registiration_date}} </p>
    <hr>
    <br>
    <p class="total-post">Toplam {{ posts|length }} gönderi</p>
    <a class="add-post-button" href="{% url 'post:addPost' %}">Gönderi oluştur</a>
    <br><br>
    
    <h4 class="header-text">Gönderiler</h4>
    <hr>
    {% if posts %}
    {% for post in posts %}
    <br>
    <div class="row">
        <div class="col-lg-8 text-align">
            <p><div class="text-muted fst-italic mb-2"> {{ post.author.username }} </div></p>
            <br><br>
            {% if post.post_image %}
                <img class="img-fluid rounded detail-img" src="{{post.post_image.url}}" alt="">
            {% endif %}
            <p><div class="post-detail">{{ post.content }} </div></p>
            <p><div class="text-muted fst-italic mb-2"> Oluşturulma tarihi : {{post.created_date}} </div></p>
            <a class="post-update-button" href="{% url 'post:updatePost' post.id %}">Gönderiyi düzenle &nbsp; <i class="fa-solid fa-pen"></i> </a>
            <a class="post-delete-button" href="{% url 'post:deletePost' post.id %}" onclick="return confirm('Bu gönderiyi silmek istediğinize emin misiniz?')">Gönderiyi sil &nbsp; <i class="fa-solid fa-trash"></i> </a>

            <hr>
        </div>
    </div>
    
        
    {% endfor %}
    {% else %}
    <div class="alert alert-danger">Henüz gönderi yok.</div>
    {% endif %}


{% endblock body %}

<script>
    function confirmDelete(PostId) {
        if (confirm("Gönderiyi silmek istediğinize emin misiniz?")) {
            
            window.location.href = '/posts/delete/' + PostId;
        } else {
            
            return false;
        }
    }
</script>
    

social_media/templates/user/change_password.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}
<h3 class="header-text">Parola değiştir</h3>
<hr>
<br>
<div class="row">
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="change-username-button-form" type="submit">Parolanı Değiştir</button>
    </form>
</div>
{% endblock body %}

social_media/templates/user/change_username.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}
<h3 class="header-text">Kullanıcı adı değiştir</h3>
<hr>
<br>
<div class="row">
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="change-username-button-form" type="submit">Kullanıcı Adını Değiştir</button>
    </form>
</div>
{% endblock body %}
    

social_media/templates/user/delete_profile_confirmation.html
{% extends 'layout.html' %}


{% block body %}
    <form method="post">
        {% csrf_token %}
        <p>Hesabınızı silmek istediğinize emin misiniz?</p>
        <div class="alert alert-danger">Bu işlem geri alınamaz!</div>
        <button class="delete-profile-confirmation" type="submit">Hesabımı Sil</button>
        <a class="cancel-button" href="{% url 'user:settings' %}">İptal</a>
    </form>
{% endblock body %}
    
        

social_media/templates/user/login.html
{% extends 'layout.html' %}


{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="form-items">
        <br><br>
        <h3>Giriş Yap</h3>
        <hr>
        <form method="post" class="form">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="login-form-button">Giriş Yap</button>
        </form>

    </div>
</div>
{% endblock body %}
    

social_media/templates/user/profileAuthor.html
{% extends 'layout.html' %}
{% load static %}


{% block body %}
    <h2 class="header-text">Kullanıcı profili</h2>
    <hr>
    <br>
    <img class="profile-photo" src="{% static 'img/placeholder.png' %}" alt="Profile Photo">
    <br>
    <br>
    
    <div class="follower">
        <div class="text-container">
            <p class="follower-text">Takipçi: {{ followers_count }}</p>
            <p class="follow-text">Takip: </p>
        </div>
        <a class="follow-button" href="">Takip et</a>        
    </div>
    <br>

    <hr>
    <p class="profile-text">Kullanıcı adı : &nbsp; {{author.username}} </p>
    <p class="profile-text">Kayıt olma tarihi : &nbsp; {{registiration_date}} </p>
    <hr>
    <br>
    <p class="total-post">Toplam {{ posts|length }} gönderi</p>
    <br>
    
    <h4 class="header-text">Kullanıcının gönderileri</h4>
    <hr>
    {% if posts %}
    {% for post in posts %}
    <br>
    <div class="row">
        <div class="col-lg-8 text-align">
            <p><div class="text-muted fst-italic mb-2"> {{ post.author.username }} </div></p>
            <p><div class="post-detail">{{ post.content }} </div></p>
            <p><div class="text-muted fst-italic mb-2"> Oluşturulma tarihi : {{post.created_date}} </div></p>
            <hr>
        </div>
    </div>

    {% endfor %}
    {% else %}
    <div class="alert alert-danger">Henüz gönderi yok.</div>
    {% endif %}
{% endblock body %}
    

social_media/templates/user/register.html
{% extends 'layout.html' %}


{% block body %}
{% load crispy_forms_tags %}
    <div class="row">
        <div class="form-items">
            <br><br>
            <h3>Kayıt Ol</h3>
            <hr>
            <form method="post" class="form">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="register-form-button">Kayıt Ol</button>
            </form>

        </div>
    </div>
{% endblock body %}
    

social_media/templates/user/settings.html
{% extends 'layout.html' %}

{% block body %}
    <h2 class="header-text">Ayarlar</h2>
    <hr>
    <br>
    <h4 class="header-text">Kullanıcı adı değiştir</h4>
    <a class="change-username-button" href="{% url 'user:change_username' %}">Kullanıcı adı değiştir</a>
    <hr>
    <br>
    <br>
    <h4 class="header-text">Parola değiştir</h4>
    <a class="change-password-button" href="{% url 'user:change_password' %}">Parola değiştir</a>
    <hr>
    <br>
    <br>
    <h4 class="header-text">Hesabı Sil</h4>
    <a class="delete-profile-button" href="{% url 'user:delete_profile' %}">Hesabı Sil</a>
{% endblock body %}
    