social_media/post/urls.py
from django.urls import path, include
from post import views
import social_media.settings 
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from .views import ModelViewSet

app_name = "post"

router = DefaultRouter()
router.register(r'posts', ModelViewSet)

urlpatterns = [
    path('', views.posts, name="posts"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('addpost/', views.addPost, name="addPost"),
    path('update/<int:id>', views.updatePost, name="updatePost"),
    path('delete/<int:id>', views.deletePost, name="deletePost"),

]
urlpatterns += static(social_media.settings.MEDIA_URL, document_root=social_media.settings.MEDIA_ROOT)

social_media/social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from post import views
import social_media.settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from post.views import ModelViewSet
from user.views import UserModelViewSet

router = DefaultRouter()
router.register(r'posts', ModelViewSet)
router.register(r'user_profiles', UserModelViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('user/', include("user.urls")),
    path('posts/', include("post.urls")),
    path('api/', include(router.urls), name='api'),
    
]
urlpatterns += static(social_media.settings.MEDIA_URL, document_root=social_media.settings.MEDIA_ROOT)

social_media/user/urls.py
from django.urls import path, include
from user import views

from rest_framework.routers import DefaultRouter
from .views import UserModelViewSet

app_name = "user"

router = DefaultRouter()
router.register(r'user_profiles', UserModelViewSet)

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('register/', views.register, name="register"),
    path('logout/', views.logoutUser, name="logout"),
    path('profile/', views.profileUser, name="profileUser"),
    path('profile_author/<int:author_id>/', views.profileAuthor, name="profileAuthor"),
    path('settings/', views.userSettings, name="settings"),
    path('change_username/', views.change_username, name="change_username"),
    path('change_password/', views.change_password, name="change_password"),
    path('delete_profile/', views.delete_profile, name="delete_profile"),
]

social_media/post/models.py
from django.db import models

class Post(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, verbose_name="Yazar")
    post_image = models.FileField(verbose_name="Resim Ekle", blank=True, null=True)
    content = models.CharField(max_length=10000, null=True, blank=True, verbose_name="İçerik")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma tarihi")

    def __str__(self):
        return self.content

social_media/post/forms.py
from django import forms
from post.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["content", "post_image"]

social_media/post/views.py
from django.shortcuts import render,redirect, get_object_or_404
from post.models import Post
from post.forms import PostForm
from django.contrib import messages

from rest_framework import viewsets
from .models import Post
from .serializers import ModelSerializer

def index(request):
    return render(request, "index.html")

def posts(request):
    posts = Post.objects.all()
    return render(request, "posts/posts.html", {"posts":posts})

def dashboard(request):
    if not request.user.is_authenticated:
        messages.info(request, "Bu sayfaya erişmek için giriş yapmalısınız.")
        return redirect("user:login")
    
    posts = Post.objects.filter(author = request.user)
    context = {
        "posts":posts,
    }

    return render(request, "posts/dashboard.html", context)

def addPost(request):
    if not request.user.is_authenticated:
        messages.info(request, "Gönderi ekleyebilmek için giriş yapmalısınız.")
        return redirect("user:login")
    
    form = PostForm(request.POST or None, request.FILES or None)
    
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        messages.success(request, "Gönderi başarıyla oluşturuldu")
        return redirect("user:profileUser")


    return render(request, "posts/addPost.html", {"form":form})

def updatePost(request, id):
    if not request.user.is_authenticated:
        messages.info(request, "Gönderi düzenleyebilmek için giriş yapmalısınız.")
        return redirect("user:login")
    post = get_object_or_404(Post, id = id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        messages.success(request, "Gönderi başarıyla güncellendi")
        return redirect("user:profileUser")

    return render(request, "posts/updatePost.html", {"form":form})

def deletePost(request, id):
    if not request.user.is_authenticated:
        messages.info(request, "Gönderi silebilmek için giriş yapmalısınız.")
        return redirect("user:login")
    post = get_object_or_404(Post, id = id)
    post.delete()
    messages.success(request, "Gönderi başarıyla silindi")
    return redirect("user:profileUser")


# Rest Framework ------------------------------------


class ModelViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = ModelSerializer

social_media/templates/posts/addPost.html
{% extends 'layout.html' %}

{% block body %}
    {% load crispy_forms_tags %}
    <div class="row">
        <div class="form-item">
            <h2 class="header-text">Gönderi Oluştur</h2>
            <hr>
            <br>
            <form method="post" class="post-form" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="add-post-button-form">Gönderi oluştur</button>
            </form>
        </div>
    </div>
{% endblock body %}
    

social_media/templates/posts/dashboard.html
{% extends 'layout.html' %}


{% block body %}
<p class="total-post">Toplam {{ posts|length }} gönderi</p>
<a class="add-post-button" href="{% url 'post:addPost' %}">Gönderi oluştur</a>
<br><br>

<h4 class="header-text">Gönderilerim</h4>
<hr>
{% if posts %}
<div class="dashboard-list">
{% for post in posts %}
<br>
<div class="row">
    <div class="col-xl-8 text-align">
        <p><div class="text-muted fst-italic mb-2"> {{ post.author.username }} </div></p>  
        <br>
        {% if post.post_image %}
            <img class="img-fluid rounded detail-img" src="{{post.post_image.url}}" alt="">
        {% endif %}
        <br><br>
        <p><div class="post-detail">{{ post.content }} </div></p>
        <p><div class="text-muted fst-italic mb-2"> Oluşturulma tarihi : {{post.created_date}} </div></p>
        <a class="post-update-button" href="{% url 'post:updatePost' post.id %}">Gönderiyi düzenle &nbsp; <i class="fa-solid fa-pen"></i> </a>
        <a class="post-delete-button" href="{% url 'post:deletePost' post.id %}" onclick="return confirm('Bu gönderiyi silmek istediğinize emin misiniz?')">Gönderiyi sil &nbsp; <i class="fa-solid fa-trash"></i> </a>
        <br><br>
        <hr>
        <br>
    </div>
    {% endfor %}
</div> 
</div>

       
{% else %}
    <div class="alert alert-danger">Henüz gönderi yok.</div>
{% endif %}
    
{% endblock body %}
    

social_media/templates/posts/posts.html
{% extends 'layout.html' %}


{% block body %}
    <h2>Gönderiler</h2>
    <hr>
    <br>
    
    {% if posts %}
        <div class="post-list">
        {% for post in posts %}
            <div class="row">
                
                    <div class="col-lg-8 text-align">
                        <p><div class="text-muted fst-italic mb-2">Yazar : 
                            {% if post.author.username == request.user.username %}
                                <a href="{% url 'user:profileUser' %}"> {{ post.author.username }}</a>
                            {% else %}
                                <a href="{% url 'user:profileAuthor' author_id=post.author.id %}"> {{ post.author.username }}</a>
                            {% endif %}
                            <br><br><br>
                            {% if post.post_image %}
                                <img class="img-fluid rounded detail-img" src="{{post.post_image.url}}" alt="">
                            {% endif %}
                        </div></p>
                        <br>
                        <a class="post-detail" href=""><p class="post-content" href="">{{post.content}} </p></a>
                        <br>
                        <p><div class="text-muted fst-italic mb-2">Oluşturulma tarihi : {{post.created_date}} </div></p>
                        <br>
                        <hr>
                        <br>
                    </div>
                
                
            </div>
        {% endfor %}
    </div>
  
    {% else %}
    <div class="alert alert-danger">Henüz gönderi yok.</div>
    {% endif %}
        
{% endblock body %}

social_media/templates/posts/updatePost.html
{% extends 'layout.html' %}

{% block body %}
    {% load crispy_forms_tags %}
    <div class="row">
        <div class="form-item">
            <h2 class="header-text">Gönderi Düzenle</h2>
            <hr>
            <br>
            <form method="post" class="post-form">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="add-post-button-form">Gönderi düzenle</button>
            </form>
        </div>
    </div>
{% endblock body %}